name: Build and Release

on:
  push:
    branches:
      - main
    path:
      - 'main/**'
  #   tags:
  #     - 'v*'  # 匹配 v 开头的标签，如 v1.0.0

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: tag
        run: echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: esp32c3
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v6.0
          target: esp32c3
          command: |
            idf.py build && \
            python -m esptool --chip esp32c3 merge_bin -o Top-AMS-esp32c3.bin \
              --flash_mode dio --flash_freq 80m --flash_size 4MB \
              0x0 build/bootloader/bootloader.bin \
              0x10000 build/Top-AMS.bin \
              0x8000 build/partition_table/partition-table.bin

      # - name: esp32s3
      #   uses: espressif/esp-idf-ci-action@v1
      #   with:
      #     esp_idf_version: release-v6.0
      #     target: esp32s3
      #     command: |
      #       idf.py build && \
      #       python -m esptool --chip esp32s3 merge_bin -o Top-AMS-esp32s3.bin \
      #         --flash_mode dio --flash_freq 80m --flash_size 16MB \
      #         0x0 build/bootloader/bootloader.bin \
      #         0x10000 build/Top-AMS.bin \
      #         0x8000 build/partition_table/partition-table.bin

      # 上传产物 artifacts
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          # artifact名字，页面上显示的名字
          name: Top-AMS
          # 需要上传的路径，可以是文件、文件夹，支持通配符
          path: Top-AMS*.bin
